version: "3"
services:
  app:
    container_name: cookbook
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"